---
abstract: 'Hex to color name converter'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ColorNamer
provides:
  App::ColorNamer:
    file: lib/App/ColorNamer.pm
    version: 0.0101
requires:
  Class::Data::Accessor: 0.04004
  Convert::Color: 0.07
resources:
  license: http://dev.perl.org/licenses/
version: 0.0101
